apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: backend-tests-java-quarkus-odmuoynx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: backend-tests-java-quarkus-odmuoynx 
  name: backend-tests-java-quarkus-odmuoynx
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: backend-tests-java-quarkus-odmuoynx 
